config/routes.rb
Seatyourself2::Application.routes.draw do

  resources :guests, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]

  resources :restaurants do
    resources :reservations
  end

  resources :guests do
    resources :reservations
  end

  root :to => "restaurants#index"

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	has_secure_password
	has_many :reservations
	has_many :restaurants, :through => :reservations
	validates_presence_of :first_name
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :guest
	validates :number_of_guests, :numericality => { :only_integer => true, :greater_than_or_equal_to => 1 }
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :guests, :through => :reservations
	validates :name, :address, :category, :summary, :presence => true

	def opening_hour
		11
	end

	def closing_hour
		20
	end

	def time_slots
		reservation_interval = 1.hour

		start_time = Time.zone.now + 10.minutes
		start_time = Time.zone.at((start_time.to_f / reservation_interval).ceil * reservation_interval)
		start_time = [start_time, start_time.change(hour: opening_hour)].max
		end_time = (start_time + 3.days).change(hour: closing_hour)

		all_times = []

		a_time = start_time

		begin
			all_times << a_time

			a_time += reservation_interval

			if (a_time + reservation_interval) > a_time.change(hour: closing_hour)
				a_time = (a_time + 1.day).change(hour: opening_hour)
			end
		end while a_time < end_time

		all_times
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_guest
  	@current_guest ||= Guest.find(session[:guest_id]) if session[:guest_id]
  end

  helper_method :current_guest

  def ensure_logged_in
  	unless current_guest
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
before_filter :ensure_logged_in, :only => [:show]

  def new
  	@guest = Guest.new
  end


  def show
    @guest = Guest.find(params[:id])

  end

  def create
  	@guest = Guest.new(guest_params)
  	if @guest.save
  		redirect_to restaurants_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

 private

def guest_params
	params.require(:guest).permit(:first_name, :last_name, :email, :telephone, :password, :password_confirmation)
end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_filter :load_restaurant, except: [:index]
  before_filter :load_guest, except: [:index, :create]
	before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]

  def index
    if params[:guest_id]
      @object = Guest.find(params[:guest_id])
    elsif params[:restaurant_id]
      @object = Restaurant.find(params[:restaurant_id])
    end
    @reservations = @object.reservations.all
  end


  def show
  	@reservation = Reservation.find(params[:id])
  end

  def create
  	@reservation = @restaurant.reservations.build(reservation_params)
  	@reservation.guest_id = current_guest.id

  	if @reservation.save
  		redirect_to restaurants_path, notice: 'Reservation created successfully'
  	else

  		render :action => :show
  	end
  end

 def destroy
 	@reservation = Reservation.find(params[:id])
 	@reservation.destroy
 end


private

def reservation_params
	params.require(:reservation).permit(:time, :date, :restaurant_id, :guest_id, :number_of_guests)
end

def load_restaurant
	@restaurant = Restaurant.find(params[:restaurant_id])
end

def load_guest
  @guest = Guest.find(params[:guest_id])
end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_filter :ensure_logged_in, :only => [:show]

  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])

  	if current_guest
  		@reservation = @restaurant.reservations.build
  	end
  end

  def new
  	@restaurant = Restaurant.new
  end

def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_url
    else
      render :new
    end
  end

  def edit
  	@restaurant = Restaurant.find(params[:id])
  end


def update
	@restaurant = Restaurant.find(params[:id])

	if @restaurant.update_attributes(restaurant_params)
		redirect_to restaurant_path(@restaurant)
	else
		render :edit
	end
end



 private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :summary, :url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	guest = Guest.find_by_email(params[:email])
  	if guest && guest.authenticate(params[:password])
  		session[:guest_id] = guest.id
  		redirect_to restaurants_url, :notice => "Logged in!"
  	else
  		render "new"
  	end
  end

  def destroy
  	session[:guest_id] = nil
  	redirect_to restaurants_url, :notice => "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def nice_datetime(datetime)
		datetime.strftime("%A %B #{datetime.day.ordinalize} %Y, %l:%M %p").sub(/(\d)([a-z]+)/, '\1<sup>\2</sup>').html_safe

	end

end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/guests/create.html.erb
<h1>Guests#create</h1>
<p>Find me in app/views/guests/create.html.erb</p>

app/views/guests/new.html.erb
<h1>Sign up!</h1>

<%= form_for @guest do |f| %>
<div class="field">
	<%= f.label :first_name %><br />
	<%= f.text_field :first_name %>
</div>

<div class="field">
	 <%= f.label :last_name %><br />
	 <%= f.text_field :last_name %><br />
</div>

<div class="field">
	 <%= f.label :email %><br />
	 <%= f.text_field :email %><br />
</div>

<div class="field">
	<%= f.label :telephone %><br />
	<%= f.telephone_field :telephone %>
</div>

<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation  %><br />
	<%= f.password_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit %></div>

<% end %>

app/views/guests/show.html.erb
<br />
<h1>Welcome, <%= @guest[:first_name].capitalize %>!</h1><br />

<h2>Here are your upcoming reservations:</h2>

<br/>

<% current_guest.reservations.each do |r| %>
	<strong><%= r.restaurant.name %></strong><br />
	<em><%= r.restaurant.address %></em><br />
	<strong>Date & Time: </strong><%= r.time %><br />
	<strong>Number of Guests:</strong> <%= r.number_of_guests %><br /><br />


	<% end %>

<button><%= link_to "Back to Restaurants", restaurants_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="guestinfo">
	<% if current_guest %>
	Signed in as <%= current_guest.first_name.capitalize %> | <%= link_to "My Profile", guest_path(current_guest) %> | <%= link_to "Log out", session_path("current"), :method => :delete %></br>
  	<% else %>
  		<%= link_to "Log in", new_session_path %>	or <%= link_to "Sign up", new_guest_path %>
  	<% end %>
  </div>



<%= yield %>

 <%= params %>

</body>
</html>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h2>Reservations</h2>
<% @reservations.each do |r| %>
	<strong><%= r.restaurant.name %></strong><br />
	<em><%= r.restaurant.address %></em><br /><br />
	<strong>Guest Name: </strong><%= r.guest.first_name %> <%= r.guest.last_name %><br />
	<strong>Date & Time: </strong><%= r.time %><br />
	<strong>Number of Guests:</strong> <%= r.number_of_guests %>
<% end %>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <br><br><h2>You have <%= pluralize(@restaurant.errors.count, "error") %>.</h2><br />
      	<h4>This restaurant cannot be saved because:</h4>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <% end %>

<%= form_for(@restaurant) do |f| %>

<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :url %><br />
	<%= f.text_field :url %>
</div>

<div class="field">
	<%= f.label :address %><br />
	<%= f.text_field :address %>
</div>

<div class="field">
	<%= f.label :category %><br />
	<%= f.text_field :category %>
</div>

<div class="field">
	<%= f.label :summary %><br />
	<%= f.text_area :summary %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back to Restaurants', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="wrap">
	<!-- <h1><p style="margin-top: 20px"><img src="http://wwwdelivery.superstock.com/WI/223/1538/PreviewComp/SuperStock_1538R-49845.jpg" width="100" height="100"> Seat Yourself </p></h1> -->

<br>
<center><img src="http://images.monstermarketplace.com/custom-made-wood-signs/please-seat-yourself-sign-8-5-x-16-75-800x425.jpg" width="250" height="180"></center>

<!-- <img src="yourImageUrl.jpeg" style="position: absolute; top: 10px; left: 10px;"/>  -->


	<% @restaurants.each do |restaurant| %>
	<div class="box">

		<div style="float: left">
			<img src="<%= restaurant[:url] %>" style="height: 75px; margin-right: 15px; border: 2px solid black"/>
		</div>

		<div>
			<%= link_to restaurant[:name], "/restaurants/#{restaurant.id}" %></br>
			<%= restaurant[:address] %></br>
			<em>Category: <%= restaurant[:category] %></em></br>
			<%= restaurant[:summary][0..50] %>...<%= link_to "[see more]", "/restaurants/#{restaurant.id}" %></br>
		</div>

	</div>



<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<button><%= link_to 'Back to Restaurant', restaurants_path %></button>

app/views/restaurants/show.html.erb
<br>
<strong><h3><%= @restaurant[:name] %></h3></strong><button><%= link_to "Edit Restaurant", edit_restaurant_path %></button>  |  <button> <%= link_to "Back to Restaurants", restaurants_path %></button></br>
<br>

<div class="border">
</br>
<img src="<%= @restaurant[:url] %>"/><br />



<p><section>
  		<strong>Address: </strong><%= @restaurant[:address] %><br><br>
  		<em><strong>Category: </strong><%= @restaurant[:category] %></em><br><br>
  		<strong>Summary: </strong><%= @restaurant[:summary] %><br><br>
</section></p>

<% if current_guest %>


<div class="reservation">
	<h3>Reservations</h3></div><br>
	<%= form_for([@restaurant, @reservation]) do |f| %>
		<div class="field">
			<%= f.label "Reservation date" %><br />
			<%= f.select :time, @restaurant.time_slots.map{ |dt| [nice_datetime(dt), dt] } %>
		</div><br />

		<div class="field">
			<%= f.label :number_of_guests %><br />
			<%= f.number_field :number_of_guests %>
		</div><br />

		<div class"actions">
			<%= f.submit %>
		</div>

	<% end %>



	<% end %>